import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * AILmanac uses a single autogenerated sidebar driven by the folder structure
 * under docs/. Order and labels are controlled per-folder via _category_.json,
 * and per-page via front-matter (sidebar_position / sidebar_label).
 *
 * This means adding a page = creating a Markdown file. No manual link lists to
 * keep in sync, and `onBrokenLinks: 'throw'` guarantees nothing dangles.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
